#!/bin/bash

# Our Plugins, installed in the pathogen ./bundle directory
cd ~/.vim/bundle

# CTRL-P and its dependencies
git clone https://github.com/MarcWeber/vim-addon-mw-utils.git

# ack is a grep alternative. There's a vim plugin.
git clone https://github.com/mileszs/ack.vim.git

# Create HTML using css expressions
git clone git://github.com/tristen/vim-sparkup.git

# Snippets, highlighting and file type detection for RSpec
git clone https://github.com/vim-scripts/Specky.git

# Snippets for many languages (hit tab)
git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/tomtom/tlib_vim.git
git clone https://github.com/garbas/vim-snipmate.git
git clone git@github.com:honza/vim-snippets.git # Has the actual snippet files

# Automatically add block endings for ruby
git clone git://github.com/tpope/vim-endwise.git

# Easily change parenthesis, brackets, quotes, etc...
#git clone git://github.com/tpope/vim-surround.git

# An older version is included with vim. We want the newest.
git clone git://github.com/vim-ruby/vim-ruby.git

# Vim has basic JavaScript support, but this might be better
git clone https://github.com/pangloss/vim-javascript.git
