#!/bin/bash

# add tmp dir
mkdir ~/.vim-tmp

# add backup dir
mkdir ~/.vim-backup

# Plugins are installed in the pathogen ./bundle directory
cd ~/.vim/bundle

# Snippets for many languages (hit tab)
git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/tomtom/tlib_vim.git
git clone https://github.com/garbas/vim-snipmate.git
git clone https://github.com/vim-scripts/Specky.git            # Rspec
git clone https://github.com/honza/vim-snippets.git            # Has the actual snippet files

git clone git://github.com/jpalardy/vim-slime.git              # slime support (send text to external apps)
git clone git://github.com/mkitt/tabline.vim.git               # Numbered tabs
git clone git://github.com/neo4j-contrib/cypher-vim-syntax.git
git clone git://github.com/ntpeters/vim-better-whitespace.git  # Automatically remove whitespace from files
git clone git@github.com:djoshea/vim-autoread.git
git clone git@github.com:elzr/vim-json.git
git clone git@github.com:logosity/vimfiles.git

git clone https://github.com/MarcWeber/vim-addon-mw-utils.git  # CTRL-P and its dependencies
git clone https://github.com/flazz/vim-colorschemes.git        # add (a lot) more colors
git clone https://github.com/hashivim/vim-terraform.git
git clone https://github.com/kyuhi/vim-emoji-complete
git clone https://github.com/pangloss/vim-javascript.git
git clone https://github.com/plasticboy/vim-markdown.git
git clone https://github.com/tpope/vim-endwise.git             # Automatically add block endings for ruby
git clone https://github.com/tristen/vim-sparkup.git           # Create HTML using css expressions
git clone https://github.com/vim-ruby/vim-ruby.git             # get latest version
git clone https://github.com/vim-scripts/VimClojure.git
git clone https://github.com/vim-syntastic/syntastic.git       # syntax error checking
